### ISSUE TITLE
ng2-password-strength-ba r/index"' has no exported member 'PasswordStrengthBar

### ISSUE THREAD

**Issue by dotnetexpert** [rnadler/ng2-password-strength-bar#7]
after upgrading ClI iam getting this

node_modules/ng2-password-strength-ba
r/index"' has no exported member 'PasswordStrengthBar

**Comment by rnadler** [comment]
Please see the README.md notes:

1.1.x Version Update Note

If you upgrade from v1.0.x to v1.1.x you will need to change the **PasswordStrengthBar** import. There are two options:

1. Change to **PasswordStrengthBarModule** and add this to the imports section of the @NgModule metadata instead of the declarations (shown below), or
2. Change to **PasswordStrengthBarComponent** and update the name in the declarations section to match.

**Comment by dotnetexpert** [comment]
Changed to PasswordStrengthBarComponent. and it solved the issue. thanks
